[package]
name = "humility-cmd-spirot"
version = "0.1.0"
edition = "2021"
description = "SP to RoT SPI communications"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
hif = { git = "https://github.com/oxidecomputer/hif" }
clap = { version = "3.0.12", features = ["derive", "env"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
parse_int = "0.4.0"
indicatif = "0.15"
log = {version = "0.4.8", features = ["std"]}
sprockets-common = { path = "../../../sprockets/common", features = ["rand"]}
hubpack = { rev = "df08cc3a6e1f97381cd0472ae348e310f0119e25", git = "https://github.com/cbiffle/hubpack.git"}
serde = { version = "1.0.136", features = ["derive"]  }
serde-big-array = { version = "0.3.2" }
