[package]
name = "humility"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
gimli = "0.20.0"
fallible-iterator = "0.2.0"
probe-rs = "0.6.1"
log = {version = "0.4.8", features = ["std"]}
bitfield = "0.13.2"
clap = "2.33.0"
csv = "1.1.3"
serde = "1.0.106"
parse_int = "0.4.0"
