[package]
name = "humility"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
gimli = "0.20.0"
fallible-iterator = "0.2.0"

#
# For now, we depend on the itm branch of probe-rs, but only for the
# read_swv() function in the session (and more generally, for its
# implementation of SWV.  As soon as we can get these changes elsewhere, this
# dependency should be changed!
#
probe-rs = { git = "https://github.com/probe-rs/probe-rs.git", branch = "itm" }

log = {version = "0.4.8", features = ["std"]}
bitfield = "0.13.2"
clap = "2.33.0"
csv = "1.1.3"
serde = "1.0.106"
parse_int = "0.4.0"
goblin = "0.2.1"
capstone = "0.7.0"
rustc-demangle = "0.1.16"
structopt = "0.3"
