[package]
name = "humility"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gimli = "0.20.0"
fallible-iterator = "0.2.0"
probe-rs = "0.6.1"
log = "0.4.8"
env_logger = "0.7.1"
bitfield = "0.13.2"
